name: Server CI Workflow
on:
  push:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./api
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: install
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: lint
        run: npm run lint
        working-directory: ${{env.working-directory}}

      - name: test
        run: npm run test
        working-directory: ${{env.working-directory}}
